#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

coffeedoc -o docs src && \
./node_modules/coffee-script/bin/coffee -o lib -c src && \
git add --all && \
git commit -m "autocommit" && \
git push -u origin master

